In [4]:
import numpy as np
import random
from collections import deque
import copy

In [5]:
class Coord:
    def __init__(self, r, c):
        self.row = r
        self.col = c

In [6]:
size = 9
grid = np.array([
            [1, 2, 3, 4, 5, 6, 7, 8, 9],
            [4, 5, 6, 7, 8, 9, 1, 2, 3],
            [7, 8, 9, 1, 2, 3, 4, 5, 6],
            [2, 3, 4, 5, 6, 7, 8, 9, 1],
            [5, 6, 7, 8, 9, 1, 2, 3, 4],
            [8, 9, 1, 2, 3, 4, 5, 6, 7],
            [3, 4, 5, 6, 7, 8, 9, 1, 2],
            [6, 7, 8, 9, 1, 2, 3, 4, 5],
            [9, 1, 2, 3, 4, 5, 6, 7, 8]
        ])

In [7]:
def swap(c1, c2):
    temp = grid[c1.row][c1.col]
    grid[c1.row][c1.col] = grid[c2.row][c2.col]
    grid[c2.row][c2.col] = temp

In [8]:
def swapRows(r1, r2):
    for i in range(size):
        swap(Coord(r1, i), Coord(r2, i))

In [9]:
def swapCols(c1, c2):
    for i in range(size):
        swap(Coord(i, c1), Coord(i, c2))

In [10]:
def flipHorizontally():
    nb_flip = int(size / 2)
    for i in range(nb_flip):
        swapRows(i, size - i - 1)

In [11]:
def flipVertically():
    nb_flip = int(size / 2)
    for i in range(nb_flip):
        swapCols(i, size - i - 1)

In [12]:
def flipBackwardDiagonal():
    for row in range(size):
        col = row + 1
        while col < size:
#             print((row, col), (col, row))
            swap(Coord(row, col), Coord(col, row))
            col = col + 1

In [13]:
def flipForwardDiagonal():
    for col in range(size):
        for row in range(size - 1 - col):
#             print((row, col), (size - 1 - col, size - 1 - row))
            swap(Coord(row, col), Coord(size - 1 - col, size - 1 - row))

In [14]:
def rowsAndColsAreValid():
    rowSet = set()
    colSet = set()
    
    for i in range(9):
        for j in range(9):
            rowSet.add(grid[i][j])
            colSet.add(grid[j][i])
                    
        if len(rowSet) != size or len(colSet) != size:
            return False
        else:
            rowSet.clear()
            colSet.clear()
    
    return True

In [28]:
def squaresAreValid():
    squareSet = set()
    
    # For each square
    for squareRow in range(0, 7, 3):
        for squareColumn in range(0, 7, 3):
            
            # For each 9 numbers in small square
            for row in range(squareRow, squareRow + 3):
                for column in range(squareColumn, squareColumn + 3):
                    print(row, column)
                    squareSet.add(grid[row][column])

            if len(squareSet) != 9:
#                 print("Square ({},{}) is wrong!".format(squareRow, squareColumn))
#                 print(squareSet)
                return False
            else:
                squareSet.clear()
                
    return True
    

In [29]:
def isValid():
    return rowsAndColsAreValid() and squaresAreValid()

In [17]:
FLIP_OPS = [flipForwardDiagonal, flipBackwardDiagonal, flipHorizontally, flipVertically]
SWAP_OPS = [swapRows, swapCols]

In [18]:
NB_OPS = 5000
SQUARE_SIZE = 3
SUDOKU_SIZE = 9

In [19]:
OP_COUNT = len(FLIP_OPS) + len(SWAP_OPS)

In [20]:
def generateRandomIndexes():
    # generate indexes (row, col) between 0 to 8
    square_index = random.randint(0, 2)
    first_index = SQUARE_SIZE * square_index + random.randint(0, 2)
    second_index = (SQUARE_SIZE * square_index + (first_index + random.randint(0, 2))) % SUDOKU_SIZE
#     print(first_index, second_index)
    return first_index, second_index

In [21]:
def randomizeSudoku():
    for i in range(NB_OPS):
        randomizeOneStep()
    
    while not isValid():
        randomizeOneStep()

In [22]:
def randomizeOneStep():
    index = random.randint(0, OP_COUNT - 1)
    if index <= 3:
        FLIP_OPS[index]()
    else: # index >= 4
        random_index = generateRandomIndexes()
        SWAP_OPS[index - 4](random_index[0], random_index[1])

In [24]:
grid

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [4, 5, 6, 7, 8, 9, 1, 2, 3],
       [7, 8, 9, 1, 2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6, 7, 8, 9, 1],
       [5, 6, 7, 8, 9, 1, 2, 3, 4],
       [8, 9, 1, 2, 3, 4, 5, 6, 7],
       [3, 4, 5, 6, 7, 8, 9, 1, 2],
       [6, 7, 8, 9, 1, 2, 3, 4, 5],
       [9, 1, 2, 3, 4, 5, 6, 7, 8]])

In [30]:
isValid()

0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2
0 3
0 4
0 5
1 3
1 4
1 5
2 3
2 4
2 5
0 6
0 7
0 8
1 6
1 7
1 8
2 6
2 7
2 8
3 0
3 1
3 2
4 0
4 1
4 2
5 0
5 1
5 2
3 3
3 4
3 5
4 3
4 4
4 5
5 3
5 4
5 5
3 6
3 7
3 8
4 6
4 7
4 8
5 6
5 7
5 8
6 0
6 1
6 2
7 0
7 1
7 2
8 0
8 1
8 2
6 3
6 4
6 5
7 3
7 4
7 5
8 3
8 4
8 5
6 6
6 7
6 8
7 6
7 7
7 8
8 6
8 7
8 8


True

In [26]:
randomizeSudoku()

In [27]:
grid

array([[3, 9, 6, 8, 2, 5, 4, 7, 1],
       [5, 2, 8, 1, 4, 7, 6, 9, 3],
       [1, 7, 4, 6, 9, 3, 2, 5, 8],
       [7, 4, 1, 3, 6, 9, 8, 2, 5],
       [6, 3, 9, 2, 5, 8, 7, 1, 4],
       [2, 8, 5, 7, 1, 4, 3, 6, 9],
       [4, 1, 7, 9, 3, 6, 5, 8, 2],
       [8, 5, 2, 4, 7, 1, 9, 3, 6],
       [9, 6, 3, 5, 8, 2, 1, 4, 7]])

In [32]:
isValid()

True

# Solver

In [23]:
sudoku = np.array([
            [0, 0, 7, 4, 0, 2, 0, 0, 0],
            [8, 0, 3, 5, 0, 7, 0, 0, 1],
            [5, 4, 0, 9, 1, 0, 0, 0, 0],
            [4, 6, 1, 0, 0, 0, 2, 0, 7],
            [0, 8, 0, 0, 0, 0, 0, 6, 0],
            [7, 0, 5, 0, 0, 0, 1, 4, 3],
            [0, 0, 0, 0, 7, 9, 0, 2, 8],
            [2, 0, 0, 6, 0, 3, 9, 0, 4],
            [0, 0, 0, 8, 0, 4, 6, 0, 0],
        ])

In [24]:
def validateRow(entry, row):
    for i in sudoku[row]:
        if i == entry:
            return False
    
    return True

In [25]:
def validateColumn(entry, col):
    for i in sudoku[:, col]:
        if i == entry:
            return False
    
    return True

In [34]:
def validateSquare(entry, row, col):
    squareRow = int(row / SQUARE_SIZE) * SQUARE_SIZE
    squareColumn = int(col / SQUARE_SIZE) * SQUARE_SIZE
    
    # For 9 numbers in small square
    for row in range(squareRow, squareRow + 3):
        for column in range(squareColumn, squareColumn + 3):
            if sudoku[row][column] == entry:
                return False
    return True

In [35]:
validateSquare(7, 0, 7)

0 6
0 7
0 8
1 6
1 7
1 8
2 6
2 7
2 8


True

In [89]:
def valueIsLegal(entry, row, column):
        return validateRow(entry, row) and validateColumn(entry, column) and validateSquare(entry, row, column)

In [69]:
def getZeroIndexes():
    zeroIndexes = []
    for row in range(SUDOKU_SIZE):
        for column in range(SUDOKU_SIZE):
            if sudoku[row][column] == 0:
                zeroIndexes.append((row, column))
    return deque(zeroIndexes)

In [151]:
sudoku = np.array([
            [0, 0, 7, 4, 0, 2, 0, 0, 0],
            [8, 0, 3, 5, 0, 7, 0, 0, 1],
            [5, 4, 0, 9, 1, 0, 0, 0, 0],
            [4, 6, 1, 0, 0, 0, 2, 0, 7],
            [0, 8, 0, 0, 0, 0, 0, 6, 0],
            [7, 0, 5, 0, 0, 0, 1, 4, 3],
            [0, 0, 0, 0, 7, 9, 0, 2, 8],
            [2, 0, 0, 6, 0, 3, 9, 0, 4],
            [0, 0, 0, 8, 0, 4, 6, 0, 0],
        ])

zeros = getZeroIndexes()
grid = np.zeros_like(sudoku)

def solveSudoku(zeroIndexes, grid):
    print()
    if len(zeroIndexes) == 0:
        print("Return cuz zeroIndexes is 0")
        return True
    
    currentIndex = zeroIndexes.popleft()
    row = currentIndex[0]
    col = currentIndex[1]
    print("Current row {}, col {}".format(row, col))
    
    for entry in range(1, size + 1):
        if valueIsLegal(entry, row, col):
            print("valueIsLegal: entry {}, row {}, col {}".format(entry, row, col))
            sudoku[row][col] = entry
            grid[row][col] = entry
            indexCopy = copy.deepcopy(zeroIndexes)
            print("Return with indexCopy len {}".format(len(indexCopy)))
             
            if solveSudoku(indexCopy, grid):
                sudoku[row][col] = 0
                return True

    sudoku[row][col] = 0
    return False
    
    

In [152]:
solveSudoku(zeros, grid)


Current row 0, col 0
valueIsLegal: entry 1, row 0, col 0
Return with indexCopy len 44

Current row 0, col 1
valueIsLegal: entry 9, row 0, col 1
Return with indexCopy len 43

Current row 0, col 4
valueIsLegal: entry 6, row 0, col 4
Return with indexCopy len 42

Current row 0, col 6
valueIsLegal: entry 8, row 0, col 6
Return with indexCopy len 41

Current row 0, col 7
valueIsLegal: entry 8, row 0, col 4
Return with indexCopy len 42

Current row 0, col 6
valueIsLegal: entry 6, row 0, col 0
Return with indexCopy len 44

Current row 0, col 1
valueIsLegal: entry 1, row 0, col 1
Return with indexCopy len 43

Current row 0, col 4
valueIsLegal: entry 8, row 0, col 4
Return with indexCopy len 42

Current row 0, col 6
valueIsLegal: entry 9, row 0, col 1
Return with indexCopy len 43

Current row 0, col 4
valueIsLegal: entry 8, row 0, col 4
Return with indexCopy len 42

Current row 0, col 6
valueIsLegal: entry 9, row 0, col 0
Return with indexCopy len 44

Current row 0, col 1
valueIsLegal: entry 1

False

In [153]:
grid

array([[9, 1, 0, 0, 8, 0, 8, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [154]:
sudoku

array([[0, 0, 7, 4, 0, 2, 0, 0, 0],
       [8, 0, 3, 5, 0, 7, 0, 0, 1],
       [5, 4, 0, 9, 1, 0, 0, 0, 0],
       [4, 6, 1, 0, 0, 0, 2, 0, 7],
       [0, 8, 0, 0, 0, 0, 0, 6, 0],
       [7, 0, 5, 0, 0, 0, 1, 4, 3],
       [0, 0, 0, 0, 7, 9, 0, 2, 8],
       [2, 0, 0, 6, 0, 3, 9, 0, 4],
       [0, 0, 0, 8, 0, 4, 6, 0, 0]])

In [66]:
np.zeros_like(sudoku)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [102]:
def fact(n):
    if n == 0:
        return 1
    else:
        return n * fact(n-1)

In [104]:
fact(4)

24